version: '3.8'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - db
      - cache
    environment:
      - REDIS_HOST=cache
      - DB_HOST=db
  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - db_data:/var/lib/postgresql/data
  cache:
    build: ./cache
    ports:
      - "6379:6379"
volumes:
  db_data:
