version: '3.8'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - db
      - cache
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
      - REDIS_HOST=cache
      - DB_HOST=${DB_HOST}
  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
  cache:
    build: ./cache
    ports:
      - "6379:6379"
volumes:
  db_data: